zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: ["agentic RL"] # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: mimo-v2.5-pro
  language: Chinese

source:
  arxiv:
    category: ["cs.AI","cs.CV","cs.LG","cs.CL","cs.IR"]

reranker:
  local:
    model: jinaai/jina-embeddings-v5-text-nano-retrieval
    encode_kwargs:
      task: retrieval
      prompt_name: document
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    model: gemini-embedding-001
    batch_size: 100

executor:
  debug: ${oc.env:DEBUG,null}
  source: ['arxiv']
  reranker: local
  max_paper_num: 20
  send_empty: true
